{
  printWidth: 100,
  tabWidth: 4,
  singleQuote: true,
  semi: true,
  jsxSingleQuote: true,
  quoteProps: as-needed,
  trailingComma: all,
  bracketSpacing: true,
  bracketSameLine: true,
  arrowParens: avoid,
}